#!/bin/bash

echo "================================================================"
echo " Safari Extension Builder Guide"
echo "================================================================"
echo ""
echo "Note: This script will NOT build the Safari extension on Linux."
echo "You MUST run this on a Mac with Xcode installed."
echo ""
echo "Steps to convert this extension for Safari on your Mac:"
echo "1. Copy this entire EXTENSION folder to your Mac."
echo "2. Open Terminal on your Mac."
echo "3. Run the following command inside this directory:"
echo ""
echo "   xcrun safari-web-extension-converter ."
echo ""
echo "4. The converter will automatically create an Xcode project."
echo "5. Open the generated project in Xcode, and click the 'Build and Run' (Play) button."
echo "6. Enable the extension in Safari > Preferences > Extensions."
echo ""
echo "================================================================"
